// Automatically generated by astro-icon
// 46c0f5ed0258f7bda8dd352f311d6b9f21ae74826788195d89758cb745b4c215

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "check"
		| "copy"
		| "funnel"
		| "grid"
		| "image"
		| "info"
		| "list"
		| "logo"
		| "spotify-logo-fill"
		| "x";
}