// Automatically generated by astro-icon
// 8f9bf97ec13f39455c66d8617bfb9f4929c42dccb0dc3be0c2be4cb70e590893

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "funnel"
		| "grid"
		| "image"
		| "info"
		| "list"
		| "logo"
		| "spotify-logo-fill"
		| "x";
}