// Automatically generated by astro-icon
// dd1ab893d730ee36059aa88adedc248fec5ca022981a65a4f95beb63e5cf33b2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "funnel"
		| "info"
		| "list"
		| "logo"
		| "spotify-logo-fill"
		| "x";
}